# Python Web App to Linux on Azure
# Build a Python WebApp and deploy it to Azure as a Linux WebApp.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - main

name: Build and deploy Python app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    # setup python
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # install dependencies
    - name: python install
      working-directory: .
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3.7-venv
        python -m venv --copies antenv
        source antenv/bin/activate
        pip install setuptools
        pip install -r 
    
    # Upload artificats
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: |
          .
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    # Download artifacts
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: .  
    
    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_e0130029 }}

    - uses: azure/appservice-settings@v1
      with:
        app-name: sushdemo1
        general-settings-json: '{"linuxFxVersion": "PYTHON|3.7"}' #'General configuration settings as Key Value pairs'
        app-settings-json: '[{ "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }]'

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: sushdemo1
        package: .

    # Azure logout
    - name: logout
      run: |
        az logout